# https://docs.github.com/en/actions

name: "Integrate"

on:
  pull_request: null
  push:
    branches:
      - "master"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    continue-on-error: true

    strategy:
      matrix:
        language:
          - "de"
          - "en"

    steps:
      - name: "checkout"
        uses: "actions/checkout@v4"
        with:
          path: "conc"

      - name: "info"
        run: |
          pwd
          ls
          cd conc
          pwd
          ls
          git log -n 3 --oneline

      - name: "Merge to main HEAD"
        run: |
          cd conc
          git branch
          git remotes -v
          git merge --no-ff --no-commit origin/master
          git reset
          git diff
