# https://docs.github.com/en/actions

name: "Integrate"

on:
  pull_request: null
  push:
    branches:
      - "master"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    continue-on-error: true

    strategy:
      matrix:
        language:
          - "de"
          - "en"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          path: "conc"

      - name: "env"
        run: env

      - name: "ls"
        run: ls

      - name: "Merge to master HEAD"
        run: |
          ls
          cd conc
          ls
          echo === show
          git show HEAD
          echo === log
          git log -n 2
          echo === merge
          git merge --no-ff --no-commit origin/master
          git reset
          git diff
